### ISSUE TITLE
Specify rng explicitly in step function

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/pgx#1043]
- Currently, step fn is deterministic even in stochastic env (as intended)
- This is useful for reproducible experiments
- However, when you run perfect simulator in planning, this may cause "information leak" about true randomness behind the current observation
- To explicitly deal with this, we may update API to v2 and add "rng" arg to step function

**Comment by sotetsuk** [comment]
#1058

**Comment by carlosgmartin** [comment]
Coincidentally, I recently wrote about the same issue in the context of the [jumanji](https://github.com/instadeepai/jumanji) library: https://github.com/instadeepai/jumanji/issues/211.

**Comment by sotetsuk** [comment]
This is implemented in #1058 and now we are testing its using experience.
If you are interested, you can checkout to `sotetsuk/v2` branch and test it.
I suppose this will be merged soon (at least within this month)
