### ISSUE TITLE
underpromotion moves for black and whiter should be different

### ISSUE THREAD

**Issue by XintianHan** [sotetsuk/pgx#1065]
https://github.com/sotetsuk/pgx/blob/main/pgx/_src/chess_utils.py#L14
I feel that here should also include a case for the white player. Now there is only a condition for the black player
```
if from_ % 8 == 6:
    to = from_ + jnp.int8([+1, +9, -7])[dir_]
```
That means we should add an additional case
```
if from_ % 8 == 1:
    to = from_ + jnp.int8([-1, -9, +7])[dir_]
```

**Comment by sotetsuk** [comment]
Thank you for your comments! Could you provide an example of wrong move case?

**Comment by sotetsuk** [comment]
We really appreciate if you could kindly give an bug example like this:

https://github.com/sotetsuk/pgx/blob/main/tests/test_chess.py#L659

**Comment by sotetsuk** [comment]
Note that, the board flips every turn. So I suppose our chess program appropriately deal with the black pawn moves.
