### ISSUE TITLE
alphazero one game search in mult devices

### ISSUE THREAD

**Issue by Nightbringers** [sotetsuk/pgx#1141]
when selfplay it was mult games in  mult devices.  But if I want play with alphazero, and I have mult devices, one game. How can I accelerate the speed of every move by use mult devices?  Not just use one device.

**Comment by sotetsuk** [comment]
Good point. We are engaged in this problem and we will release a new version of the algorithm in a few months.
I think the most famous approach is to use virtual loss.

As this issue itself is not related to environments (but algorithms), we close this issue.
