### ISSUE TITLE
AlphaZero training on standard chess 

### ISSUE THREAD

**Issue by janetwise** [sotetsuk/pgx#1163]
Does your AlphaZero example code support standard chess training besides the current 5 games? I tried to remove the baseline model eval as there isn't any baseline model for chess but the training didn't work. 

The Gardner chess training did work. Thank you!

**Comment by sotetsuk** [comment]
What do you mean by "didn't work?" Any runtime error?

**Comment by janetwise** [comment]
> What do you mean by "didn't work?" Any runtime error?

Thank you for your reply! I tried to run under example/alphazero: python train.py env_id="chess" seed=0.

As the chess game doesn't come with the baseline model (there are 5 baseline models not including 8x8 chess) to do eval with, I then commented out the related eval code and tried to get around the baseline eval part in train.py. Then it had some errors in the transformer code... Didn't really spend lot of time on it. What would you suggest update the code to make it work with chess?

Are you able to run/test your alphaZero training on 8x8 chess? Or do you plan to provide a baseline model for chess so the alphazero training can run?

**Comment by sotetsuk** [comment]
> Then it had some errors in the transformer code...

We do not use transformer. So I'm not sure what kind of errors you have.

We have a plan to provide powerful opponents for chess, shogi and Go.
For shogi and Go, we already have powerful opponents in private and they will be public in a few months.
For chess, we are preparing opponent models now. 
We hope we can provide it in 2024.
