### ISSUE TITLE
[Kuhn Poker] Simplify the implementation

### ISSUE THREAD

**Issue by Egiob** [sotetsuk/pgx#1169]
Hey, multiple implementations of Kuhn Poker out there ([open_spiel ](https://github.com/google-deepmind/open_spiel/blob/b8c2ff8e9a4f5dad9b179217f740ddb0df967f7c/open_spiel/games/kuhn_poker.cc)for instance) use only two actions (pass, bet) instead of the four considered in pgx (call, bet, check, fold). In fact we can group bet/call and check/fold without ambiguity for this game. 

Would you be interested by this simplification? I would be happy to open a PR if you are!

**Comment by sotetsuk** [comment]
Hi, thank you for your comment! 🙏
I'm positive for this change.
There are only five scenarios. Four actions are redundant.

If you kindly submit a PR, we'll receive it.
We also really appreciate if you can list up some implementations or papers which use two actions to support this change (in addition to open spiel)
