### ISSUE TITLE
go game ownership

### ISSUE THREAD

**Issue by Nightbringers** [sotetsuk/pgx#1183]
The ownership of each territory, whether it belongs to the black or white side, and how much one side is leading over the other. It's  
important to go service. Can you implement this?

**Comment by sotetsuk** [comment]
Hi, thank you for comments. What do you mean by "go service?"

**Comment by Nightbringers** [comment]
go web service, it use pgx go as the backend engine, user can play with each other , or play with AI,  Position Assessment is an important function.

**Comment by sotetsuk** [comment]
Hi thank you for the clarification but I feel like it's not something pgx is responsible for. Given the current go board, you can compute it by other libraries I guess.
