### ISSUE TITLE
[BridgeBidding] Add observe function

### ISSUE THREAD

**Issue by harukaki** [sotetsuk/pgx#705]
Open Spielの実装を参考にobservationを実装
#108

**Comment by harukaki** [comment]
入力：player_id: int
出力：各チームのvul, 自分の手札, 行動のヒストリー

**Comment by harukaki** [comment]
![スクリーンショット 2023-04-03 11 18 52](https://user-images.githubusercontent.com/82935276/229396955-6358fdea-9325-4b38-a504-89f7b60fb276.png)

**Comment by sotetsuk** [comment]
出典へのリンクも貼ってもらえますか？

**Comment by sotetsuk** [comment]
OpenSpielの特徴量にするんですか？FBの先行研究って話だったと思うんですけど…

**Comment by harukaki** [comment]
上のコメントをアップデートしました！
observationの返り値は先行研究の特徴量表現に合わせるべきでしょうか？
例えばbid historyは、pgxの実装上ではプレイされた順に行動を並べているだけですが、先行研究ではどのプレイヤーがどの行動をしたのかという表現になっています。また、available action(合法手)等も返すべきでしょうか？

**Comment by sotetsuk** [comment]
先行研究に合わせたいですね。。。。。。。
元々、そういう話だったと思ってるので。
合法手マスクも必要です。

**Comment by sotetsuk** [comment]
どのプレイヤーがビッドしたかも復元できるって話しませんでしたっけ？？

**Comment by harukaki** [comment]
すいません、話を覚えていなかったです...
特徴量表現を先行研究に合わせる場合、はdeepmindの表現を使うことになります。
Fairの表現は不十分なものになっていて、全観測を一意に表せていません。
observationの返り値は以下の 情報の行列表現になるという認識であっていますか？
- deepmindの表現、(vul, hand, bid history)
- 合法手マスク

**Comment by sotetsuk** [comment]
@harukaki リンクちゃんと貼れてないです。。。

**Comment by sotetsuk** [comment]
@harukaki じゃあDeepMindの方でやりましょう。
合法手マスクは、他の環境の実装と同様に実装してください。 `legal_action_mask`
