### ISSUE TITLE
[BridgeBidding] TODOs

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/pgx#714]
- [x] reward
  - [x] illegal action penalty
- [ ] duplicate
- [ ] large DDS result table

Check OpenSpiel implementation

**Comment by harukaki** [comment]
open spielはimpを使っているか？

**Comment by harukaki** [comment]
### large DDS result tableに関して、
FAIRが公開しているデータセットを使用する方針にする
https://github.com/facebookresearch/jps
このデータベースから読み込んでハッシュテーブルを作成する関数を作ればいい？

**Comment by sotetsuk** [comment]
@harukaki 

自分で作った方が早くないですか？前に小さいデータセット作ったときのコードここに貼ってもらえます？

上のデータセットも追加で利用可能にするのはいいですけど、それをデファクトにしちゃうとサイズ増やせない印象になるので、やめたいです。あとライセンスもついてないし。

**Comment by harukaki** [comment]
@sotetsuk 
https://colab.research.google.com/drive/1fWnsKLzvxL5g_kpSiwLn7PiLhr5VuRBl?usp=sharing
これになります。FAIRデータセットを使おうとした理由はデータセットを作成する時間が結構かかりそうだからです。
上記の実装では、dds_table()でhand一つに対してかかる計算時間はざっくり0.2~0.4秒ぐらいでした。
0.4 * 2,500,000 = 1,000,000 second = 277 hour
ぐらいかかってしまいます。

**Comment by sotetsuk** [comment]
んーでも待ってるだけなら別に待ってもいいと思うんですけどね。。。

まあ上のデータも使えるようにするのは全然いいと思います！

**Comment by sotetsuk** [comment]
あとまあ単純に複数プロセス実行すれば等倍で早くなりますし。４並列で数日待つくらいなら別にいいんじゃないかなって思いますけど

**Comment by harukaki** [comment]
なるほどです。一旦並列で作る方針に取り組んでみます。

**Comment by sotetsuk** [comment]
別に並列で作るのもコードそんなに書き換える必要なくて、手元で違うシードで複数実行するだけでいいと思います！

**Comment by sotetsuk** [comment]
データ作るのと並列で、どういうAPIで使うのか、案が欲しいですね@harukaki

**Comment by sotetsuk** [comment]
なるほど🤔じゃあ一旦それに倣っていいかもですね！でも最終的にduplicateも使えないと困るので、ユーザ側でできるのか確認はしたいですね！@harukaki

**Comment by sotetsuk** [comment]
はい！そうですね！ワークスペースとかで試してみてもらえると一番いいです！@harukaki 
その様子如何でどうするか考えますか。簡単なラッパーを用意するとかも候補になると思います！

**Comment by harukaki** [comment]
illegal actionに対しては-7600を返す

**Comment by harukaki** [comment]
### hash table API

- hash tableを追加できるか
- hash を指定できるか
-

**Comment by harukaki** [comment]
@sotetsuk 
`vmap`と`duplicate`の順番についての指摘がいまいち理解できていないです。
#756では`vmap`された`init`で生成された初期状態にたいして`vmap`した`duplicate`で同じだけのduplicate状態を作っていました。この動作において`duplicate`と`vmap`を入れ替えるとはどういう意味合いかもう一度お聞きできるとありがたいです！

**Comment by sotetsuk** [comment]
@harukaki コード何回か直しましたがこれでいけてるとおもいます

**Comment by harukaki** [comment]
@sotetsuk 
なるほどです！ありがとうございます。
多分理解できたと思うのでPRで取り組んでみようとしてみます！

**Comment by harukaki** [comment]
@sotetsuk 
duplicate対戦については、新たに実装した`duplicate_step`、`duplicate_init`があれば実現できると思います。
それぞれ確認が必要ですが、これらをどのように提供するのがいいでしょう？

- `pgx.bridge_bidding`内で実装する
- また違うファイルで実装して提供する

**Comment by sotetsuk** [comment]
うーん悩ましいですね。

使っていくうちに仕様変わる可能性もあるので、 

`experimental/bridge_bidding.py`

以下でやりますか？ @harukaki

**Comment by harukaki** [comment]
@sotetsuk そうですね！承知しました。
`experimental/bridge_bidding.py`内で実装すべきことは上記の3つの必要な関数のみというイメージで大丈夫でしょうか？
またそれぞれテスト等もできたらと思うんですがそれはdoctestでやるイメージでいいでしょうか？
以上ができたら一旦duplicateのAPIは完了したとして、次のhash table等のTODOに移ろうと思っていますがご意見ありますでしょうか？

**Comment by sotetsuk** [comment]
はいその３つ実装してdoctest追加してでいいと思います！
