### ISSUE TITLE
Update `dataclass` implementation

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/pgx#743]
To surpass warnings

**Comment by rhaps0dy** [comment]
My suggestion, in case it's useful (from another project I'm working on):

```py
def register_dataclass_as_pytree(Cls: Type):
    def flatten_attrs(inst: Cls) -> tuple[Iterable[Any], tuple[str, ...]]:
        fields = dataclasses.fields(inst)
        names = tuple(f.name for f in fields)
        return (getattr(inst, n) for n in names), names

    def unflatten_attrs(names, values) -> Cls:
        return Cls(**dict(zip(names, values)))

    jax.tree_util.register_pytree_node(Cls, flatten_attrs, unflatten_attrs)
    return Cls


@dataclass_transform()
def dataclass_frozen_pytree(Cls: Type):
    """Decorator to make a frozen dataclass and register it as a PyTree."""
    dataCls = dataclasses.dataclass(frozen=True, slots=True)(Cls)
    register_dataclass_as_pytree(dataCls)
    return dataCls
```

**Comment by rhaps0dy** [comment]
Even better, you can pull in `chex` and use `@chex.dataclass(...)` https://github.com/deepmind/chex

**Comment by sotetsuk** [comment]
Thank you for your suggestion! 👍 

Currently, we are not using other JAX-based libraries, including chex as it may require a higher JAX version.
As JAX can be used in cluster system managed by administrators,
some Pgx users may not be able to upgrade their JAX environment by themselves.

We will investigate possible directions (including your two suggestions!) and upgrade dataclass during this month 👍 
Any other suggestion or opinion is more than welcome!

**Comment by sotetsuk** [comment]
@rhaps0dy We replaced it by chex! #787 Thank you for your help! :)

**Comment by rhaps0dy** [comment]
> I have tested in various environments and found that the flax-based one behaves more stably 😂

Oh no, that sucks 😢 I thought dataclasses would be pretty stable in all cases, since their functionality mostly comes from Python; guess not!
