### ISSUE TITLE
[BridgeBidding] How to provide a large dataset

### ISSUE THREAD

**Issue by harukaki** [sotetsuk/pgx#778]
250,000,000 sampleのcsvファイルは容量が286.44 MB あったのでそのままではリモートリポジトリに載せられない

**Comment by harukaki** [comment]
@sotetsuk 
何かご意見あればお聞きしたいです！

**Comment by sotetsuk** [comment]
どこかからダウンロードされるようにするとかですかね？？
他には思いつかないです🤔
なにかあるかな。。。別になにかやり方思いつきます？@harukaki

**Comment by harukaki** [comment]
@sotetsuk 
僕も外部からダウンロードしてもらう方法しか思いついてないです！一旦その方向で提供したいと思います。
共有するためのツールとしてはgoogle driveで大丈夫そうでしょうか？

**Comment by sotetsuk** [comment]
んーgithubでホストできたら一番いいですけどね。。。そこはちょっと検証しましょう。

**Comment by harukaki** [comment]
@sotetsuk 
すいません、githubでホストするの意味合いが理解できていないです...

**Comment by sotetsuk** [comment]
Git lfsとかgithub sssetsとかの候補があります

**Comment by harukaki** [comment]
なるほどです、ちょっと調べます！

**Comment by sotetsuk** [comment]
あとは大きいデータセットを

`def download_bridge_bidding_dds_results()`

とかつくってダウンロードできるようにしてください。
たぶん requests 使うのがいいと思います。
**追加で必要な依存関係は関数内でimportしてください**（動的にインポートする）

@harukaki

**Comment by harukaki** [comment]
はい、ありがとうございます！
ダウンロードできるデータとしてはいかが考えられますが全てをダウンロードしてくる実装でいいでしょうか？

- handとdds resultのデータが載っているcsvファイル
- 2000000 dataが入ったtrain用のdds_hash_table.npy, 500000 dataが入ったtest用のnpy

**Comment by sotetsuk** [comment]
サイズどれくらいかにもよりますけど。
まあ一旦全部詰めて圧縮したらいいと思います！
