### ISSUE TITLE
[AnimalShogi] Implement 千日手

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/pgx#860]
http://img-cdn.jg.jugem.jp/202/1663686/20110922_2052732.png

**Comment by youyou-ku** [comment]
やねうらおう（https://github.com/yaneurao/YaneuraOu）

- zobrist key定義部：https://github.com/yaneurao/YaneuraOu/blob/f7f218115ed94215be60cf2fdd6ef3545b376b28/source/position.cpp#L22
- 初期化：https://github.com/yaneurao/YaneuraOu/blob/f7f218115ed94215be60cf2fdd6ef3545b376b28/source/position.cpp#L95
- 指定盤面でのhash生成？：https://github.com/yaneurao/YaneuraOu/blob/f7f218115ed94215be60cf2fdd6ef3545b376b28/source/position.cpp#L411
- 盤面遷移時の処理。hash更新も行う：https://github.com/yaneurao/YaneuraOu/blob/f7f218115ed94215be60cf2fdd6ef3545b376b28/source/position.cpp#L1061

**Comment by sotetsuk** [comment]
https://yaneuraou.yaneu.com/2015/12/16/%E9%80%A3%E8%BC%89%E3%82%84%E3%81%AD%E3%81%86%E3%82%89%E7%8E%8Bmini%E3%81%A7%E9%81%8A%E3%81%BC%E3%81%86%EF%BC%817%E6%97%A5%E7%9B%AE/
