### ISSUE TITLE
[BridgeBidding] Match the implementation of `observation` and `action` to openspiel 

### ISSUE THREAD

**Issue by harukaki** [sotetsuk/pgx#888]
pgxのbridgebiddingの`observation`と`action`の表現をopenspielの実装に合わせる

- [x] action, observationのopenspiel実装をcheck
- [x] action実装
- [x] observation実装
- [x] 削減した観測でのSL

**Comment by harukaki** [comment]
このcolabで実験的にチェック
https://colab.research.google.com/drive/115aIe-g4jUDmS53JHRPb1UtEF3xNJAdZ?hl=ja#scrollTo=y5lrts7Tmtev

action
- 0~51: handを配るための行動(openspiel実装ではhandを配るフェーズを用意している)
- 52~89: biddingの行動
   52: pass
   53: double
   54: redouble
   55~89: bid (1♧ -> 1♢ -> 1♡ -> 1♤ -> 1N -> ... -> 7N)

observation
- 571次元
   deepmindのbridge論文で発表していたobservation(480次元)と違う。https://arxiv.org/abs/2011.14124
   ![image](https://github.com/sotetsuk/pgx/assets/82935276/42f9a279-9a0f-4cae-a71a-b47e014ada8c)
- Openspielが提供しているbridgeのsupervised learningのコードでは571次元のまま学習している
   https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/bridge_supervised_learning.py

**Comment by harukaki** [comment]
@sotetsuk 
actionにおいて、pgxとopenspielではhandを配るフェーズを含むか含まないかで表現がかなり異なるため合わせる必要がないように感じますがいかがでしょう？合わせるとしたらpass, double, redouble, bidの順番に添字を与えることかなと思います。pgxではbid, pass, double, redoubleの順に添字を与えています。https://github.com/sotetsuk/pgx/blob/a9160a15bbc1549ad52e5db55494cbc0b98a5f26/pgx/bridge_bidding.py#L54-L59

observationに関しては、合わせる必要があるかもですが論文等に記述がなく調べずらくて困っています。
何かご意見、助言いただければありがたいです！

**Comment by sotetsuk** [comment]
すみません！全然意味がわからないです😭

まず、Spielは配るフェーズがあるが、Pgxはないという理解であってますか？
そうなら、Spielはなぜあると思いますか？@harukaki

**Comment by harukaki** [comment]
@sotetsuk 
はい、合っています！
openspielのリポジトリで説明を見つけられていないので勝手な解釈になりますが、spielで配り方がある理由はduplicate matchを考慮しているのかなと思っています。handの配り方を行動にすることで、ランダムにhandを配るのも、duplicateのように事前にhandを指定して使うのもユーザーの自由だという実装かなと思いました。

Pgxではdds results計算済みのhandを用い、事前にhandの配り方が指定されているので、handを自由に配るフェーズは作ることができないです。

**Comment by sotetsuk** [comment]
なるほど、じゃあ行動に関しては、最初の52次元を無視して、残りを同じ順番にしてテストしやすくするのがいいかもですね！@harukaki

**Comment by sotetsuk** [comment]
Observationに関しては残りの増えた次元が何かとかはソースコード読みに行くしかない気がします。
それを読んだ上でどちらにするか決めるとか？
あるいは、SL学習のコードをpgxの特徴量と同じに変換できるならそっちを変えてもいいかもですけど。。。

**Comment by harukaki** [comment]
openspielのObservation実装

517次元だが、bidding phaseだけでなくplaying phaseの観測も含む。ところどころ不明点がある。
| Index | Description |
|:---:|:----|
| `obs[0]` | bidding phaseかどうか |
| `obs[1]` | playing phaseかどうか |
| `obs[2, 3]` | 何を表すかわからない、bidding中は基本的に0 |
| `obs[4, 8]` | vulかどうか |
| `obs[8, 12]` | 各プレイヤーがopening bid以前にpassをしたかどうか |
| `obs[12, 24]` | 1♧に対してどのプレイヤーがbid, double, redoubleをしたか |
| ... | ... |
| `obs[420, 432]` | 7♤に対してどのプレイヤーがbid, double, redoubleをしたか |
| `obs[432, 484]` | 13-hot vector indicating the cards we hold |
| `obs[484, 517]` | おそらくplayingのための観測 |

**Comment by harukaki** [comment]
C++コードは読めず、colab上で実験的にわかったopenspielのobsの実装が上の表。
517次元に増えていたのはplaying phaseのための観測も含んでいるから。おそらくbidding phaseのための観測は484次元

#852 のpgxのobsとの違いは以下

- pgxではbidding phaseしかサポートしないので今がどのphaseかどうかを示す観測はいらない(openspielのobsの1, 2bit目)
- vulかどうかはpgxでは2 bitで表現するが、openspielでは4 bit (2 bitで表現できる)
- Bidの表現が異なる
   openspiel : 1♧(Bid, Double, Redouble) -> 1♢(Bid, Double, Redouble) -> ... -> 7NT(Bid, Double, Redouble)
   pgx : Bid(1♧, 1♢, ... , 7NT) -> Double(1♧, 1♢, ... , 7NT) -> Redouble(1♧, 1♢, ... , 7NT)
- 各プレイヤーを表現するbitがことなる
   openspiel : [自分, 左隣, 対面, 右隣]
   pgx : [N, E, S, W]
- handの表現が異なる。
   openspiel : ♧2 -> ♢2 -> ♡2 -> ♤2 -> ... -> ♧A -> ♢A -> ♡A -> ♤A
   pgx :  ♧A ... ♧K -> ♢A ... ♢K -> ♡A ... ♡K -> ♤A ... ♤K

**Comment by harukaki** [comment]
@sotetsuk 
より詳細にopenspielのobsを確認しました!
obsをopenspielに合わせる方向にする上で以下のポイントがあり、ご助言いただけると幸いです。

- phaseを表すbitは必要ない
- 2 bitで表現できるvulをopenspielの4 bit表現にするのか？
- handの表現をobsだけopenspielに合わせると、pgxの内部で使用しているhandとint表現と順番が異なってしまう。(内部表現も変えるのは面倒くさそう？)

**Comment by sotetsuk** [comment]
Vulは別に大変でないなら変えたらいいと思います

**Comment by sotetsuk** [comment]
handも別に変わってもいいので変えられるなら変えてもいいと思います。

あとはspielのSLモデルをpgxで動かすのに問題ないかが気になりますね。
たとえば不要なobs次元をマスクするか削って学習したりできないか検証してみてもらえると

**Comment by harukaki** [comment]
承知です！ありがとうございます！
