### ISSUE TITLE
[Backgammon] Add dice to visualization.

### ISSUE THREAD

**Issue by nissymori** [sotetsuk/pgx#891]
Playを評価するために, サイコロも可視化に入れた方が良い.
できれば既にplayしたものは薄くなるという仕様があると良い.

**Comment by OkanoShinri** [comment]
> できれば既にplayしたものは薄くなるという仕様があると良い.

これって過去に振られたサイコロを表示するということでしょうか？
もしそうなら、Stateでサイコロのログ等を保持しておかないときつい気がします

**Comment by sotetsuk** [comment]
@nissymori

**Comment by sotetsuk** [comment]
@nissymori 可視化の仕様ある程度決めてくれた方がいいかもしれないです。あと、そのために必要な情報をどこから取ったらいいのか書いてもらえると。

**Comment by OkanoShinri** [comment]
雑ですけどこんなイメージでしょうか

![スクリーンショット 2023-05-26 203651](https://github.com/sotetsuk/pgx/assets/72956592/c42ec17c-dc8c-4ce7-a49f-b30982c24ca7)

**Comment by sotetsuk** [comment]
簡単なのはプレイ可能なダイスだけ表示してプレイしたダイスは消えてくのが楽そうかもですね

４つのときどう見えるかだけ気をつけてもらえれば

**Comment by nissymori** [comment]
> 簡単なのはプレイ可能なダイスだけ表示してプレイしたダイスは消えてくのが楽そうかもですね
> 
> ４つのときどう見えるかだけ気をつけてもらえれば

確かに, 過去どんな行動をしたのかは見えないので, 消すのでいい気がしました！

**Comment by OkanoShinri** [comment]
理解しました
試作品作ってみます！
