### ISSUE TITLE
Termination in Leduc Holdem

### ISSUE THREAD

**Issue by Egiob** [sotetsuk/pgx#925]
Hello, in Leduc Holdem I don't quite understand why doing the `FOLD` action in the first round of betting doesn't terminate the episode.
`    terminated = round_over & (state._round == 1)`
Seems to me that's a faulty behavior, please tell me if I miss something. A possible fix could be:
`    terminated = (round_over & (state._round == 1)) | (action==FOLD) `

**Comment by sotetsuk** [comment]
Hi, Thank you for your suggestion! 🙏 

You comment makes sense.  We suppose the Leduc Holdem implementation should follow this diagram from [[Southey+05](https://arxiv.org/ftp/arxiv/papers/1207/1207.1411.pdf)]

![](https://user-images.githubusercontent.com/72956592/227712224-dbcb6523-f81c-4b6a-9ee8-c6611c341ed7.png)

but it does not follow the diagram.

```py
import jax
import jax.numpy as jnp
import pgx

env = pgx.make("leduc_holdem")

init_fn = jax.jit(env.init)
step_fn = jax.jit(env.step)

CALL = jnp.int32(0)
RAISE = jnp.int32(1)
FOLD = jnp.int32(2)

state = init_fn(jax.random.PRNGKey(0))
state = step_fn(state, RAISE)
assert not state.terminated
state = step_fn(state, FOLD)
assert state.terminated  # AssertionError!
```

@OkanoShinri Could you investigate it?

**Comment by OkanoShinri** [comment]
Thank you for pointing it out!
Sorry, I misunderstood the holdem rules. The current implementation is to proceed to the next round even if the player folds. I will create a PR for the fix immediately.
